import { GoogleGenAI } from '@google/genai';
import Groq from 'groq-sdk';
import { webSearch, formatSearchResultsForContext, WEB_SEARCH_FUNCTION_DECLARATION } from './webSearchService.js';

// Global cached client instances with lazy init
let geminiClient = null;
let cachedGeminiKey = null;
let groqClient = null;
let cachedGroqKey = null;

export function getActiveProviderName() {
  return 'gemini';
}

export function getGeminiClient() {
  const apiKey = (process.env.GEMINI_API_KEY || '').trim();
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not configured in environment.');
  }
  if (!geminiClient || cachedGeminiKey !== apiKey) {
    cachedGeminiKey = apiKey;
    geminiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });
  }
  return geminiClient;
}

export function getGroqClient() {
  const apiKey = (process.env.GROQ_API_KEY || '').trim();
  if (!apiKey) {
    throw new Error('GROQ_API_KEY is not configured in environment.');
  }
  if (!groqClient || cachedGroqKey !== apiKey) {
    cachedGroqKey = apiKey;
    groqClient = new Groq({ apiKey });
  }
  return groqClient;
}

/**
 * Supported Gemini models in primary order
 */
const GEMINI_MODELS = [
  'gemini-2.5-flash',
  'gemini-flash-latest',
  'gemini-3.7-flash',
  'gemini-2.5-flash-lite',
  'gemini-3.1-pro-preview',
];

/**
 * Active fallback models on Groq
 */
const GROQ_FALLBACK_MODELS = [
  'qwen/qwen3.8-27b',
  'groq/compound',
  'openai/gpt-oss-120b',
  'openai/gpt-oss-20b',
  'groq/compound-mini',
  'qwen/qwen3.6-27b',
  'allam-2-7b',
];

/**
 * Circuit Breaker State for Gemini
 */
let geminiCircuitOpenUntil = 0;
const CIRCUIT_BREAKER_COOLDOWN_MS = 60 * 1000; // 60s cooldown on 429 quota exhaustion
const PER_CALL_TIMEOUT_MS = 8000; // 8s max per individual model call

/**
 * Hard per-call timeout helper
 */
function withTimeout(promise, timeoutMs = PER_CALL_TIMEOUT_MS, errorLabel = 'LLM API Call') {
  return Promise.race([
    promise,
    new Promise((_, reject) => {
      const timer = setTimeout(() => {
        reject(new Error(`${errorLabel} timed out after ${timeoutMs}ms`));
      }, timeoutMs);
      if (timer.unref) timer.unref();
    }),
  ]);
}

export function isGeminiCircuitOpen() {
  return Date.now() < geminiCircuitOpenUntil;
}

export function tripGeminiCircuitBreaker() {
  geminiCircuitOpenUntil = Date.now() + CIRCUIT_BREAKER_COOLDOWN_MS;
  console.warn(`[Gemini Circuit Breaker] 429 quota error encountered. Opening circuit breaker for ${CIRCUIT_BREAKER_COOLDOWN_MS / 1000}s.`);
}

/**
 * Check whether web search tools should be enabled for this request.
 * Only enabled when SERPER_API_KEY is configured.
 */
function isWebSearchEnabled() {
  return Boolean((process.env.SERPER_API_KEY || '').trim());
}

/**
 * Build Gemini tools config with web_search function declaration.
 */
function getGeminiToolsConfig() {
  if (!isWebSearchEnabled()) return {};
  return {
    tools: [
      {
        functionDeclarations: [WEB_SEARCH_FUNCTION_DECLARATION],
      },
    ],
  };
}

/**
 * Extract a search query string from text generated by models without native tool execution support (e.g. Groq fallback).
 * Supports [SEARCH: query], ```web_search\nquery: "..."```, and web_search("...") patterns.
 */
export function extractSearchQueryFromText(text) {
  if (!text || typeof text !== 'string') return null;

  // 1. [SEARCH: ...] or [web_search: ...]
  const bracketMatch = text.match(/\[(?:SEARCH|web_search):\s*(.+?)\]/i);
  if (bracketMatch && bracketMatch[1]?.trim()) {
    return bracketMatch[1].trim();
  }

  // 2. ```web_search ... query: "..." ... ```
  const codeBlockMatch = text.match(/```(?:web_search|search)[\s\S]*?query:\s*["']?([^"'\r\n]+)["']?[\s\S]*?```/i);
  if (codeBlockMatch && codeBlockMatch[1]?.trim()) {
    return codeBlockMatch[1].trim();
  }

  // 3. web_search("...") or web_search(query="...")
  const fnCallMatch = text.match(/web_search\s*\(\s*(?:query\s*=\s*)?["']([^"'\r\n]+)["']\s*\)/i);
  if (fnCallMatch && fnCallMatch[1]?.trim()) {
    return fnCallMatch[1].trim();
  }

  return null;
}


/**
 * Extract a function call from a Gemini response, if present.
 * Returns { name, args } or null.
 */
function extractFunctionCall(response) {
  try {
    const candidates = response?.candidates;
    if (!candidates || candidates.length === 0) return null;
    const parts = candidates[0]?.content?.parts;
    if (!parts || parts.length === 0) return null;
    for (const part of parts) {
      if (part.functionCall) {
        return {
          name: part.functionCall.name,
          args: part.functionCall.args || {},
        };
      }
    }
  } catch (_) {
    // Fallback: no function call found
  }
  return null;
}

/**
 * Execute a tool call and return the result.
 * Currently only supports 'web_search'.
 */
async function executeToolCall(functionCall) {
  if (functionCall.name === 'web_search') {
    const query = functionCall.args?.query || '';
    console.log(`[Function Calling] Executing web_search("${query}")`);
    const searchResult = await webSearch(query);
    return {
      name: 'web_search',
      response: searchResult,
    };
  }
  return {
    name: functionCall.name,
    response: { error: `Unknown tool: ${functionCall.name}` },
  };
}

/**
 * Universal Non-Streaming Response Generator
 * Attempts Gemini first (with function calling support), automatically fails over to Groq.
 */
export async function generateResponse(
  history,
  message,
  systemPrompt = 'You are a helpful, precise multi-turn conversational AI assistant.',
  options = {}
) {
  const startTime = Date.now();

  // 1. Try Gemini (if circuit is closed)
  if (process.env.GEMINI_API_KEY && process.env.GEMINI_API_KEY.trim()) {
    if (isGeminiCircuitOpen()) {
      const remainingSec = Math.ceil((geminiCircuitOpenUntil - Date.now()) / 1000);
      console.warn(`[Gemini Circuit Breaker] Circuit is OPEN (cooling down for ${remainingSec}s). Fast-routing directly to Groq fallback.`);
    } else {
      try {
        const ai = getGeminiClient();
        const candidateModels = options?.model
          ? [options.model, ...GEMINI_MODELS.filter((m) => m !== options.model)]
          : GEMINI_MODELS;

        const contents = [
          ...history.map((m) => ({
            role: m.role === 'assistant' ? 'model' : 'user',
            parts: [{ text: m.content }],
          })),
          {
            role: 'user',
            parts: [{ text: message }],
          },
        ];

        const toolsConfig = getGeminiToolsConfig();

        for (const model of candidateModels) {
          try {
            const response = await withTimeout(
              ai.models.generateContent({
                model,
                contents,
                config: {
                  systemInstruction: systemPrompt,
                  temperature: 0.7,
                  ...toolsConfig,
                },
              }),
              PER_CALL_TIMEOUT_MS,
              `Gemini (${model})`
            );

            // Check for function call in response
            const functionCall = extractFunctionCall(response);
            let usedWebSearch = false;

            if (functionCall) {
              // Execute the tool call
              const toolResult = await executeToolCall(functionCall);
              usedWebSearch = functionCall.name === 'web_search';

              // Append function call and response to conversation, then re-generate
              const updatedContents = [
                ...contents,
                {
                  role: 'model',
                  parts: [{ functionCall: { name: functionCall.name, args: functionCall.args } }],
                },
                {
                  role: 'user',
                  parts: [{ functionResponse: { name: toolResult.name, response: toolResult.response } }],
                },
              ];

              // Second call: Gemini synthesizes a final answer using the tool results
              const synthesisResponse = await withTimeout(
                ai.models.generateContent({
                  model,
                  contents: updatedContents,
                  config: {
                    systemInstruction: systemPrompt,
                    temperature: 0.7,
                  },
                }),
                PER_CALL_TIMEOUT_MS * 2, // Allow extra time for synthesis
                `Gemini Synthesis (${model})`
              );

              const text = synthesisResponse.text || '';
              const latencyMs = Date.now() - startTime;
              const tokensEstimated = Math.ceil((text.length + message.length) / 4);

              return {
                text,
                provider: 'gemini',
                model,
                latencyMs,
                tokensEstimated,
                isFallback: false,
                usedWebSearch,
                searchQuery: functionCall.args?.query || null,
              };
            }

            // No function call — standard text response
            const text = response.text || '';
            const latencyMs = Date.now() - startTime;
            const tokensEstimated = Math.ceil((text.length + message.length) / 4);

            return {
              text,
              provider: 'gemini',
              model,
              latencyMs,
              tokensEstimated,
              isFallback: false,
              usedWebSearch: false,
            };
          } catch (err) {
            const errMsg = err?.message || String(err);
            const isQuota =
              errMsg.includes('RESOURCE_EXHAUSTED') ||
              errMsg.includes('GenerateRequestsPerDay') ||
              errMsg.includes('429') ||
              errMsg.includes('quota');

            if (isQuota) {
              tripGeminiCircuitBreaker();
              break; // Fail over immediately to Groq without trying other Gemini models
            }
          }
        }
      } catch (geminiErr) {
        console.warn('[Gemini] Generation failed, initiating Groq fallback:', geminiErr?.message || geminiErr);
      }
    }
  }

  // 2. Automatic Failover to Groq (with prompt-based web search fallback)
  if (process.env.GROQ_API_KEY && process.env.GROQ_API_KEY.trim()) {
    try {
      const groq = getGroqClient();
      const safeSystemPrompt =
        typeof systemPrompt === 'string' && systemPrompt.trim()
          ? systemPrompt.trim()
          : 'You are a helpful, precise multi-turn conversational AI assistant.';

      const messages = [
        { role: 'system', content: safeSystemPrompt },
        ...(Array.isArray(history) ? history : [])
          .filter((m) => m && m.content && typeof m.content === 'string' && m.content.trim())
          .map((m) => ({
            role: m.role === 'assistant' ? 'assistant' : 'user',
            content: m.content.trim(),
          })),
        { role: 'user', content: String(message || '').trim() || 'Hello' },
      ];

      for (const model of GROQ_FALLBACK_MODELS) {
        try {
          const completion = await withTimeout(
            groq.chat.completions.create({
              model,
              messages,
              temperature: 0.7,
              max_tokens: 1024,
            }),
            PER_CALL_TIMEOUT_MS,
            `Groq (${model})`
          );

          let text = completion.choices[0]?.message?.content || '';
          const latencyMs = Date.now() - startTime;
          let usedWebSearch = false;
          let searchQuery = null;

          // Groq fallback: Check if model requested a web search (e.g. [SEARCH: query] or ```web_search)
          const extractedQuery = extractSearchQueryFromText(text);
          if (extractedQuery && isWebSearchEnabled()) {
            searchQuery = extractedQuery;
            console.log(`[Groq Fallback] Detected search request: "${searchQuery}"`);
            const searchResult = await webSearch(searchQuery);
            const searchContext = formatSearchResultsForContext(searchResult);
            usedWebSearch = true;

            // Re-prompt Groq with search results injected
            const retryMessages = [
              ...messages,
              { role: 'assistant', content: text },
              { role: 'user', content: `Here are the web search results for "${searchQuery}":\n\n${searchContext}\n\nNow please answer the original question using these search results. Cite sources with URLs.` },
            ];

            const retryCompletion = await withTimeout(
              groq.chat.completions.create({
                model,
                messages: retryMessages,
                temperature: 0.7,
                max_tokens: 1024,
              }),
              PER_CALL_TIMEOUT_MS,
              `Groq Search Synthesis (${model})`
            );

            text = retryCompletion.choices[0]?.message?.content || text;
          }

          const tokensEstimated =
            completion.usage?.total_tokens || Math.ceil((text.length + message.length) / 4);

          return {
            text,
            provider: 'groq',
            model,
            latencyMs: Date.now() - startTime,
            tokensEstimated,
            isFallback: true,
            usedWebSearch,
            searchQuery,
          };
        } catch (groqModelErr) {
          console.warn(`[Groq Fallback] Model ${model} failed (${groqModelErr?.message}), trying next candidate...`);
        }
      }
    } catch (groqErr) {
      console.error('[Groq Fallback] Error executing fallback:', groqErr?.message || groqErr);
    }
  }

  throw new Error('LLM Generation Error: Both Gemini and fallback services are currently unavailable. Please check your API keys in .env.');
}

/**
 * Universal Streaming Response Generator
 * Streams from Gemini (with function calling), and automatically falls back to Groq.
 */
export async function generateStreamResponse(
  history,
  message,
  systemPrompt = 'You are a helpful, precise multi-turn conversational AI assistant.',
  onChunk,
  options = {}
) {
  const startTime = Date.now();

  // 1. Try Gemini Streaming (if circuit is closed)
  if (process.env.GEMINI_API_KEY && process.env.GEMINI_API_KEY.trim()) {
    if (isGeminiCircuitOpen()) {
      const remainingSec = Math.ceil((geminiCircuitOpenUntil - Date.now()) / 1000);
      console.warn(`[Gemini Stream Circuit Breaker] Circuit is OPEN (cooling down for ${remainingSec}s). Fast-routing directly to Groq stream fallback.`);
    } else {
      try {
        const ai = getGeminiClient();
        const candidateModels = options?.model
          ? [options.model, ...GEMINI_MODELS.filter((m) => m !== options.model)]
          : GEMINI_MODELS;

        const contents = [
          ...history.map((m) => ({
            role: m.role === 'assistant' ? 'model' : 'user',
            parts: [{ text: m.content }],
          })),
          {
            role: 'user',
            parts: [{ text: message }],
          },
        ];

        const toolsConfig = getGeminiToolsConfig();

        for (const model of candidateModels) {
          try {
            // First call: Non-streaming to check for function calls
            const initialResponse = await withTimeout(
              ai.models.generateContent({
                model,
                contents,
                config: {
                  systemInstruction: systemPrompt,
                  temperature: 0.7,
                  ...toolsConfig,
                },
              }),
              PER_CALL_TIMEOUT_MS,
              `Gemini Stream Init (${model})`
            );

            const functionCall = extractFunctionCall(initialResponse);

            if (functionCall) {
              // Execute the tool call
              const toolResult = await executeToolCall(functionCall);
              const usedWebSearch = functionCall.name === 'web_search';

              // Send a search indicator chunk to the client
              if (usedWebSearch) {
                onChunk(`🔍 *Searching the web for: "${functionCall.args?.query}"...*\n\n`);
              }

              // Build updated conversation with tool results
              const updatedContents = [
                ...contents,
                {
                  role: 'model',
                  parts: [{ functionCall: { name: functionCall.name, args: functionCall.args } }],
                },
                {
                  role: 'user',
                  parts: [{ functionResponse: { name: toolResult.name, response: toolResult.response } }],
                },
              ];

              // Stream the synthesis response
              const synthesisStream = await withTimeout(
                ai.models.generateContentStream({
                  model,
                  contents: updatedContents,
                  config: {
                    systemInstruction: systemPrompt,
                    temperature: 0.7,
                  },
                }),
                PER_CALL_TIMEOUT_MS * 2,
                `Gemini Synthesis Stream (${model})`
              );

              let fullText = '🔍 *Searching the web for: "' + (functionCall.args?.query || '') + '"...*\n\n';
              for await (const chunk of synthesisStream) {
                const chunkText = chunk.text || '';
                if (chunkText) {
                  fullText += chunkText;
                  onChunk(chunkText);
                }
              }

              const latencyMs = Date.now() - startTime;
              const tokensEstimated = Math.ceil((fullText.length + message.length) / 4);

              return {
                text: fullText,
                provider: 'gemini',
                model,
                latencyMs,
                tokensEstimated,
                isFallback: false,
                usedWebSearch,
                searchQuery: functionCall.args?.query || null,
              };
            }

            // No function call — stream the initial text response
            // Since we already got the non-streaming response, stream it manually
            const initialText = initialResponse.text || '';
            if (initialText) {
              onChunk(initialText);
            }

            const latencyMs = Date.now() - startTime;
            const tokensEstimated = Math.ceil((initialText.length + message.length) / 4);

            return {
              text: initialText,
              provider: 'gemini',
              model,
              latencyMs,
              tokensEstimated,
              isFallback: false,
              usedWebSearch: false,
            };
          } catch (err) {
            const errMsg = err?.message || String(err);
            const isQuota =
              errMsg.includes('RESOURCE_EXHAUSTED') ||
              errMsg.includes('GenerateRequestsPerDay') ||
              errMsg.includes('429') ||
              errMsg.includes('quota');

            if (isQuota) {
              tripGeminiCircuitBreaker();
              break; // Fail over immediately to Groq stream
            }
          }
        }
      } catch (geminiErr) {
        console.warn('[Gemini Stream] Stream failed, initiating Groq fallback:', geminiErr?.message || geminiErr);
      }
    }
  }

  // 2. Automatic Stream Failover to Groq
  if (process.env.GROQ_API_KEY && process.env.GROQ_API_KEY.trim()) {
    try {
      const groq = getGroqClient();
      const safeSystemPrompt =
        typeof systemPrompt === 'string' && systemPrompt.trim()
          ? systemPrompt.trim()
          : 'You are a helpful, precise multi-turn conversational AI assistant.';

      const messages = [
        { role: 'system', content: safeSystemPrompt },
        ...(Array.isArray(history) ? history : [])
          .filter((m) => m && m.content && typeof m.content === 'string' && m.content.trim())
          .map((m) => ({
            role: m.role === 'assistant' ? 'assistant' : 'user',
            content: m.content.trim(),
          })),
        { role: 'user', content: String(message || '').trim() || 'Hello' },
      ];

      for (const model of GROQ_FALLBACK_MODELS) {
        try {
          const stream = await withTimeout(
            groq.chat.completions.create({
              model,
              messages,
              temperature: 0.7,
              max_tokens: 1024,
              stream: true,
            }),
            PER_CALL_TIMEOUT_MS,
            `Groq Stream (${model})`
          );

          let fullText = '';
          for await (const chunk of stream) {
            const delta = chunk.choices[0]?.delta?.content || '';
            if (delta) {
              fullText += delta;
              onChunk(delta);
            }
          }

          // Groq fallback: Check if model requested a web search (e.g. [SEARCH: query] or ```web_search)
          const extractedStreamQuery = extractSearchQueryFromText(fullText);
          let usedWebSearch = false;
          let searchQuery = null;

          if (extractedStreamQuery && isWebSearchEnabled()) {
            searchQuery = extractedStreamQuery;
            console.log(`[Groq Stream Fallback] Detected search request: "${searchQuery}"`);
            const searchResult = await webSearch(searchQuery);
            const searchContext = formatSearchResultsForContext(searchResult);
            usedWebSearch = true;

            onChunk('\n\n🔍 *Searching the web...*\n\n');

            // Re-prompt Groq with search results (non-streaming then stream synthesis)
            const retryMessages = [
              ...messages,
              { role: 'assistant', content: fullText },
              { role: 'user', content: `Here are the web search results for "${searchQuery}":\n\n${searchContext}\n\nNow please answer the original question using these search results. Cite sources with URLs.` },
            ];

            const retryStream = await withTimeout(
              groq.chat.completions.create({
                model,
                messages: retryMessages,
                temperature: 0.7,
                max_tokens: 1024,
                stream: true,
              }),
              PER_CALL_TIMEOUT_MS,
              `Groq Search Synthesis Stream (${model})`
            );

            fullText = '';
            for await (const chunk of retryStream) {
              const delta = chunk.choices[0]?.delta?.content || '';
              if (delta) {
                fullText += delta;
                onChunk(delta);
              }
            }
          }

          const latencyMs = Date.now() - startTime;
          const tokensEstimated = Math.ceil((fullText.length + message.length) / 4);

          return {
            text: fullText,
            provider: 'groq',
            model,
            latencyMs,
            tokensEstimated,
            isFallback: true,
            usedWebSearch,
            searchQuery,
          };
        } catch (groqModelErr) {
          console.warn(`[Groq Stream Fallback] Model ${model} failed (${groqModelErr?.message}), trying next candidate...`);
        }
      }
    } catch (groqStreamErr) {
      console.error('[Groq Stream Fallback] Error in fallback stream:', groqStreamErr?.message || groqStreamErr);
    }
  }

  throw new Error('LLM Streaming Error: Both Gemini and fallback services are currently unavailable. Please check your API keys in .env.');
}
